name: OpenShift CI/CD Pipeline with Image Build

on:
  push:
    branches:
      - sb-2.5.x

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        env:
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USER --password-stdin
          docker build --tag rest-http-example .
          docker tag rest-http-example:latest jameszhang2019/rest-http-example:latest
          docker push jameszhang2019/rest-http-example:latest

      - name: Set up OpenShift CLI
        run: |
          curl -LO "https://mirror.openshift.com/pub/openshift-v4/clients/ocp/stable/openshift-client-linux.tar.gz"
          tar -xvf openshift-client-linux.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Login to OpenShift
        env:
          OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
          OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
        run: |
          oc login $OPENSHIFT_SERVER --token=$OPENSHIFT_TOKEN

      - name: Update Deployment with New Image
        run: |
          oc set image deployment/rest-http-example rest-http-example=docker.io/jameszhang2019/rest-http-example:latest
